
			<option value="null" active> Par Wilaya </option>
			<option undefined> ----- </option>
			<option value="adrar">Adrar</option>
			<option value="chlef">Chlef</option>
			<option value="laghouat">Laghouat</option>
			<option value="oum el boouaghi">Oum El Bouaghi</option>
			<option value="batna">Batna</option>
			<option value="bejaia">Bejaia</option>
			<option value="biskra">Biskra</option>
			<option value="bechar">Bechar</option>
			<option value="blida">Blida</option>
			<option value="bouira">Bouira</option>
			<option value="tamanrasset">Tamanrasset</option>
			<option value="tebessa">Tebessa</option>
			<option value="tlemcen">Tlemcen</option>
			<option value="tiaret">Tiaret</option>
			<option value="tizi-ouzou">Tizi-Ouzou</option>
			<option value="alger">Alger</option>
			<option value="djelfa">Djelfa</option>
			<option value="jijel">Jijel</option>
			<option value="setif">Saida</option>
			<option value="skikda">Skikda</option>
			<option value="sidi bel abbes">Sidi bel abbes</option>
			<option value="annaba">Annaba</option>
			<option value="guelma">Guelma</option>
			<option value="constantine">Constantine</option>
			<option value="médéa">Médéa</option>
			<option value="mostaganem">Mostaganem</option>
			<option value="m'sila">M'sila</option>
			<option value="mascara">Mascara</option>
			<option value="ouargla">Ouargla</option>
			<option value="oran">Oran</option>
			<option value="bayedh">Bayedh</option>
			<option value="illizi">Illizi</option>
			<option value="bordj bou arreidj">Bordj bou arreidj</option>
			<option value="boumerdes">Boumerdes</option>
			<option value="tarf">Tarf</option>
			<option value="tindouf">Tindouf</option>
			<option value="tissemsilt">Tissemsilt</option>
			<option value="el oued">El Oued</option>
			<option value="khenchela">Khenchela</option>
			<option value="souk ahras">Souk ahras</option>
			<option value="tipaza">Tipaza</option>
			<option value="mila">Mila</option>
			<option value="defla">Defla</option>
			<option value="naama">Nâama</option>
			<option value="temouchent">Temouchent</option>
			<option value="gherdaia">Gherdaia</option>
			<option value="relizane">Relizane</option>
			<option value="timimoune">Timimoune</option>
			<option value="bordj badji mokhtar">Bordj Badji mokhtar</option>
			<option value="ouled djellal">ouled djellal</option>
			<option value="beni abbes">Beni abbes</option>
			<option value="salah">Salah</option>
			<option value="guezzam">Guezzam</option>
			<option value="touggourt">Touggourt</option>
			<option value="djanet">Djanet</option>
			<option value="m'ghair">M'ghair</option>
			<option value="meniaa">Meniaa</option>
